services:
  postgres:
    image: postgres:15
    container_name: mars_postgres
    environment:
      POSTGRES_DB: mars
      POSTGRES_USER: mars_user
      POSTGRES_PASSWORD: mars_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mars_redis
    ports:
      - "6379:6379"

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mars_app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    #environment:
      #AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      #AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      #AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      #DB_HOST: postgres
      #DB_PORT: 5432
      #DB_NAME: mars
      #DB_USER: mars_user
      #DB_PASSWORD: mars_password
    #command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    #ports:
      #- "8000:8000"
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    tty: true
    command: []

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mars_worker
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ..:/app
    tty: true
    entrypoint: [ "bash", "docker/entrypoint.sh", "worker" ]
    #environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_NAME: mars
#      DB_USER: mars_user
#      DB_PASSWORD: mars_password
#    command: celery -A src.worker.celery_app worker --loglevel=info



volumes:
  postgres_data: